### ISSUE TITLE
[BUG] Ver 1.1.8-1 breaks plasma wayland

### ISSUE THREAD

**Issue by nomantis** [NVIDIA/egl-wayland#40]
## The bug

After upgrading from 1.1.7-1 logging in through sddm with plasma Wayland session selected, the desktop is fully missing. The cursor is visible and can be moved, and moving it to the top-left corner displays the blue desktop switching indicator, but no other visual elements are present and no applications can be started.

## Reproducing the bug

OS - Archlinux

Install SDDM, plasma-desktop and nvidia-dkms. Downgrade egl-wayland to ver1.1.7-1 and reboot. This time the desktop works. Upgrade egl-wayland to ver1.1.8-1, reboot and this time the above described will happen.

Haven't checked how to debug this yet, any help would be appreciated!

**Comment by knomantis** [comment]
Thanks that would be great! Tell me if I can help with anything.

**Comment by erik-kz** [comment]
Let's see how this is received https://codereview.qt-project.org/c/qt/qtwayland/+/373473

**Comment by erik-kz** [comment]
If you feel like it, you could try building qtwayland with that patch and see if it resolves your issue. It does appear to work for me.

**Comment by zhanghua000** [comment]
> If you feel like it, you could try building qtwayland with that patch and see if it resolves your issue. It does appear to work for me.

This problem still exists even rebuild qt5-wayland with your patch. But wayland-session log changes from 
```
error in client communication (pid 1342)
[destroyed object]: error 7: importing the supplied dmabufs failed
```
to
```
ProtocolException thrown:Failed to write all data
```
Full wayland-session log files generated by SDDM before and after patch:
https://gist.github.com/zhanghua000/084d3f3bca2a9f173b409adff7138f5e

**Comment by Dnnd** [comment]
It appears to me that 1.1.8 have a major bug.

Egl-wayland 1.1.8 breaks the following applications:
- Firefox-Nightly (94.0a1 (2021-09-27)) - won't start
- Alacritty (0.9.0) - won't start
- Telegram desktop - crashes after click on the image attachments
- Problems with other applications were also reported on Arch Forums (https://bbs.archlinux.org/viewtopic.php?pid=1995109#p1995109)

I'm using nvidia with PRIME Render Offloading only. Bug occurs even when the application should be launched on Intel UHD (i.e. without `__NV_PRIME_RENDER_OFFLOAD=1 __VK_LAYER_NV_optimus=NVIDIA_only __GLX_VENDOR_LIBRARY_NAME=nvidia`).

**Downgrade to 1.1.7 fixes the problem**

<details> <summary> System & Graphics Information </summary> 

```
System:
  Kernel: 5.14.8-zen1-1-zen x86_64 bits: 64 Desktop: sway 1.6.1
  Distro: Arch Linux
Graphics:
  Device-1: Intel CoffeeLake-H GT2 [UHD Graphics 630] driver: i915 v: kernel
  Device-2: NVIDIA GP107M [GeForce GTX 1050 Mobile] driver: nvidia v: 470.74
  Device-3: IMC Networks USB2.0 HD UVC WebCam type: USB driver: uvcvideo
  Display: wayland server: X.Org 1.21.1.2 compositor: sway driver:
  loaded: modesetting,nvidia resolution: 1: 1920x1080~60Hz 2: 1920x1200~60Hz
  OpenGL: renderer: Mesa Intel UHD Graphics 630 (CFL GT2) v: 4.6 Mesa 21.2.2
```
</details>
